AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  koodoo

  Sample SAM Template for koodoo

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900

Parameters:
  s3BucketParameter:
    Type: String
    Description: s3Bucket where to export csv file

Resources:
  KoodooFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - 's3:PutObject'
              Resource: !Join [ "", [ "arn:aws:s3:::", !Ref s3BucketParameter ,"/*" ] ]
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - 'ssm:GetParameters'
                - 'ssm:GetParameter'
              Resource: arn:aws:ssm:*
    Metadata:
      DockerTag: koodoo
      DockerContext: .
      Dockerfile: Dockerfile
  s3Bucket:
      Type: AWS::SSM::Parameter
      Properties:
          Name: /koodoo-s3-bucket
          Type: String
          Value: !Ref s3BucketParameter
